import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const monteserrat = localFont({
  src: "../assets/fonts/Montserrat-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Tender Tasks",
  description: "Generated by Jitendra Bakoria",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monteserrat.className}  antialiased`}>{children}</body>
    </html>
  );
}
